<?php

namespace ProdEvolBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    /*
    public function findOneByIdJoindToProduct($releaseId)
    {
        $query = $this->getEntityManager()
                ->createQuery(
                        'SELECT p,r FROM ProdEvolBundle:Product p'
                        JOIN p.)
    }
     * */
     
}
